task:
  name: ShadowHand
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:8192,${...num_envs}}
    envSpacing: 0.75
    episodeLength: 160
    resetTime: 8
    enableDebugVis: false
    aggregateMode: 1
    clipObservations: 5.0
    clipActions: 1.0
    stiffnessScale: 1.0
    forceLimitScale: 1.0
    useRelativeControl: false
    dofSpeedScale: 20.0
    actionsMovingAverage: 0.3
    controlFrequencyInv: 3
    startPositionNoise: 0.01
    startRotationNoise: 0.0
    resetPositionNoise: 0.01
    resetRotationNoise: 0.0
    resetDofPosRandomInterval: 0.2
    resetDofVelRandomInterval: 0.0
    forceScale: 1.0
    forceProbRange:
    - 0.001
    - 0.1
    forceDecay: 0.99
    forceDecayInterval: 0.08
    distRewardScale: -10.0
    rotRewardScale: 1.0
    rotEps: 0.1
    actionPenaltyScale: -0.0002
    reachGoalBonus: 250
    fallDistance: 0.24
    fallPenalty: -50.0
    objectType: block
    observationType: openai
    asymmetric_observations: true
    successTolerance: 0.4
    printNumSuccesses: false
    maxConsecutiveSuccesses: 50
    averFactor: 0.1
    asset:
      assetRoot: ../assets
      assetFileName: mjcf/open_ai_assets/hand/shadow_hand.xml
      assetFileNameBlock: urdf/objects/cube_multicolor.urdf
      assetFileNameEgg: mjcf/open_ai_assets/hand/egg.xml
      assetFileNamePen: mjcf/open_ai_assets/hand/pen.xml
    enableCameraSensors: false
  task:
    randomize: true
    randomization_params:
      frequency: 720
      observations:
        range:
        - 0
        - 0.002
        range_correlated:
        - 0
        - 0.001
        operation: additive
        distribution: gaussian
      actions:
        range:
        - 0.0
        - 0.05
        range_correlated:
        - 0
        - 0.015
        operation: additive
        distribution: gaussian
      sim_params:
        gravity:
          range:
          - 0
          - 0.4
          operation: additive
          distribution: gaussian
      actor_params:
        hand:
          color: true
          tendon_properties:
            damping:
              range:
              - 0.3
              - 3.0
              operation: scaling
              distribution: loguniform
            stiffness:
              range:
              - 0.75
              - 1.5
              operation: scaling
              distribution: loguniform
          dof_properties:
            damping:
              range:
              - 0.3
              - 3.0
              operation: scaling
              distribution: loguniform
            stiffness:
              range:
              - 0.75
              - 1.5
              operation: scaling
              distribution: loguniform
            lower:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
            upper:
              range:
              - 0
              - 0.01
              operation: additive
              distribution: gaussian
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
          rigid_shape_properties:
            friction:
              num_buckets: 250
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
        object:
          scale:
            range:
            - 0.95
            - 1.05
            operation: scaling
            distribution: uniform
            setup_only: true
          rigid_body_properties:
            mass:
              range:
              - 0.5
              - 1.5
              operation: scaling
              distribution: uniform
              setup_only: true
          rigid_shape_properties:
            friction:
              num_buckets: 250
              range:
              - 0.7
              - 1.3
              operation: scaling
              distribution: uniform
  sim:
    dt: 0.01667
    substeps: 2
    up_axis: z
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    physx:
      num_threads: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${contains:"cuda",${....sim_device}}
      num_position_iterations: 8
      num_velocity_iterations: 0
      max_gpu_contact_pairs: 8388608
      num_subscenes: ${....num_subscenes}
      contact_offset: 0.002
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      max_depenetration_velocity: 1000.0
      default_buffer_size_multiplier: 5.0
      contact_collection: 0
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 512
        activation: relu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
      rnn:
        name: lstm
        units: 1024
        layers: 1
        before_mlp: true
        layer_norm: true
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:ShadowHandAsymmLSTM,${....experiment}}
      full_experiment_name: ${.name}
      env_name: rlgpu
      multi_gpu: false
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.01
      normalize_advantage: true
      gamma: 0.998
      tau: 0.95
      learning_rate: 0.0001
      lr_schedule: adaptive
      schedule_type: standard
      kl_threshold: 0.016
      score_to_win: 100000
      max_epochs: ${resolve_default:10000,${....max_iterations}}
      save_best_after: 500
      save_frequency: 500
      print_stats: true
      grad_norm: 1.0
      entropy_coef: 0.0
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 16
      minibatch_size: 16384
      mini_epochs: 4
      critic_coef: 4
      clip_value: true
      seq_length: 4
      bounds_loss_coef: 0.0001
      central_value_config:
        minibatch_size: 32768
        mini_epochs: 4
        learning_rate: 0.0001
        kl_threshold: 0.016
        clip_value: true
        normalize_input: true
        truncate_grads: true
        network:
          name: actor_critic
          central_value: true
          mlp:
            units:
            - 512
            activation: relu
            d2rl: false
            initializer:
              name: default
            regularizer:
              name: None
          rnn:
            name: lstm
            units: 1024
            layers: 1
            before_mlp: true
            layer_norm: true
      player:
        deterministic: true
        games_num: 1000000
        print_stats: false
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
multi_gpu: false
headless: false
